language: python

python:
    - "2.7"
    - "3.6"

env:
    - DJANGO=django==1.11.*
    - DJANGO=django==2.0.*
    - DJANGO=django==2.1.*
    - DJANGO=django==2.2.*

install:
    - pip install -r test_requirements.txt --use-mirrors
    - pip install $DJANGO
    - pip install coveralls

script:
    - cd admintool_command/tests
    - ./runtests.py
    - mv .coverage ../../
    - cd ../../

matrix:
    exclude:
        - python: "3.4"
          env: DJANGO=django==1.4.*

after_success:
    - coveralls
